### ISSUE TITLE
I cloned your whole project and run the test.py by using the pre-trained model, but it comes the error with:

### ISSUE THREAD

**Issue by TingtingLi0101** [YuSuen/colorCycleGAN#1]
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    G.load_state_dict(torch.load("./checkpoints/A2BG_generator_param.pkl", map_location='cpu'))
  File "/Users/litingting/colorization_venv/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/litingting/colorization_venv/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '%'.
(colorization_venv) (base) LideMacBook-Pro:colorCycleGAN litingting$

**Comment by artorias-gh** [comment]
same error

**Comment by YuSuen** [comment]
@Lonelyearner @TingtingLi0101 This issue caused by the checkpoints corrupted during the upload.  Since the focus of my later work is not on colorization, I am sorry that the data about this repository has been lost. You can use custom data for training and testing first. Thanks.
